all: q7 q8 q9 q10 q11

q7: q7.c
	gcc -Wall -std=c99 -g -o q7 q7.c

q8: q8.c
	gcc -Wall -std=c99 -g -o q8 q8.c

q9: q9.c
	gcc -Wall -std=c99 -g -o q9 q9.c

q10: q10.c
	gcc -Wall -std=c99 -g -o q10 q10.c

q11: q11.c printChar.c
	gcc -Wall -std=c99 -g -o q11 q11.c printChar.c
