app3: app3.c
	gcc -Wall -g -o app3 app3.c

app2: app2.c
	gcc -Wall -g -o app2 app2.c

app1: app1.c
	gcc -Wall -g -o app1 app1.c

q10: q10.c
	gcc -Wall -g -o q10 q10.c

q11: q11.c printChar.c
	gcc -Wall -g -o q11 q11.c printChar.c


